[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install] 
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && gunicorn app:app --host 0.0.0.0 --port $PORT"
